### ISSUE TITLE
TypeError:

### ISSUE THREAD

**Issue by MartinLiZeqian** [EthVM/EthVM#1154]
node:internal/deps/undici/undici:11457
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /Users/zorro/workRoot/EthVM/v2/node_modules/.pnpm/registry.npmmirror.com+@squoosh+lib@0.5.3/node_modules/@squoosh/lib/build/imagequant_node-a4aafbae.wasm
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at new URL (node:internal/url:560:13)
      at new Request (node:internal/deps/undici/undici:7041:25)
      at fetch2 (node:internal/deps/undici/undici:10598:25)
      at Object.fetch (node:internal/deps/undici/undici:11455:18)
      at fetch (node:internal/process/pre_execution:230:25)
      at instantiateAsync (/Users/zorro/workRoot/EthVM/v2/node_modules/.pnpm/registry.npmmirror.com+@squoosh+lib@0.5.3/node_modules/@squoosh/lib/build/index.js:28:11469)
      at createWasm (/Users/zorro/workRoot/EthVM/v2/node_modules/.pnpm/registry.npmmirror.com+@squoosh+lib@0.5.3/node_modules/@squoosh/lib/build/index.js:28:12079)
      at /Users/zorro/workRoot/EthVM/v2/node_modules/.pnpm/registry.npmmirror.com+@squoosh+lib@0.5.3/node_modules/@squoosh/lib/build/index.js:28:35216
      at instantiateEmscriptenWasm (/Users/zorro/workRoot/EthVM/v2/node_modules/.pnpm/registry.npmmirror.com+@squoosh+lib@0.5.3/node_modules/@squoosh/lib/build/index.js:1:466) {
    input: '/Users/zorro/workRoot/EthVM/v2/node_modules/.pnpm/registry.npmmirror.com+@squoosh+lib@0.5.3/node_modules/@squoosh/lib/build/imagequant_node-a4aafbae.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by olgakup** [comment]
@MartinLiZeqian please try running this with node v.18.0.0 *specified in .nvmrc file under v2 folder
