### ISSUE TITLE
Encoding issue with Postgres / Timescale on ERC20 detector

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/EthVM#523]
* **I'm submitting a ...**
    - [ ] feature request
    - [X] bug report

* **Bug Report**
The detected exception related to encoding issues:

```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLException: java.sql.BatchUpdateException: Batch entry 12 INSERT INTO "erc20_metadata" ("address","name","symbol","decimals","total_supply") VALUES ('0x8be2847c17c8bf000d6e1326c63c8729d3ebe940','MySuperDuperTokenMySuperDuperToken','MMMMMM',3,'1000000000') ON CONFLICT ("address") DO UPDATE SET "name"=EXCLUDED."name","symbol"=EXCLUDED."symbol","decimals"=EXCLUDED."decimals","total_supply"=EXCLUDED."total_supply" was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00

	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
	... 10 more
Caused by: java.sql.SQLException: java.sql.BatchUpdateException: Batch entry 12 INSERT INTO "erc20_metadata" ("address","name","symbol","decimals","total_supply") VALUES ('0x8be2847c17c8bf000d6e1326c63c8729d3ebe940','MySuperDuperTokenMySuperDuperToken','MMMMMM',3,'1000000000') ON CONFLICT ("address") DO UPDATE SET "name"=EXCLUDED."name","symbol"=EXCLUDED."symbol","decimals"=EXCLUDED."decimals","total_supply"=EXCLUDED."total_supply" was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00  Call getNextException to see other errors in the batch.
org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00

	... 12 more
```

Below you can see a picture:

![2019-05-27-210227_3640x1047_scrot](https://user-images.githubusercontent.com/82811/58435847-e2e24080-80c2-11e9-9243-cc3e02aad3e0.png)

**Comment by brianmcgee** [comment]
This still has not been resolved. I have however changed the contract sink to be tolerant of errors and to put bad entries into a dead letter topic, allowing it to continue on with writing other entries to the database.
