### ISSUE TITLE
U.block must not be null

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/EthVM#526]
* **I'm submitting a ...**
    - [ ] feature request
    - [x] bug report

* **Bug Report**
    I obtained the following exception on the parity-source connector:

Connector settings:

```
connector.class=com.ethvm.kafka.connect.sources.web3.ParitySourceConnector
schema.registry.url=http://kafka-schema-registry:8081
max.request.size=52428800
tasks.max=3
ws.url=ws://ip:port
producer.max.request.size=52428800
name=parity-source
```

Exception:

```
java.lang.IllegalStateException: u.block must not be null
	at com.ethvm.kafka.connect.sources.web3.sources.ParityBlocksSource.fetchRange(ParityBlocksSource.kt:164)
	at com.ethvm.kafka.connect.sources.web3.sources.AbstractParityEntitySource.poll(AbstractParityEntitySource.kt:55)
	at com.ethvm.kafka.connect.sources.web3.ParitySourceTask.poll(ParitySourceTask.kt:65)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by brianmcgee** [comment]
This looks like there was an error response from Parity that we did not handle correctly. Will address this once we have merged the refinements to the Parity connector. For now a restart will usually resolve this as the error was likely related to the Parity being under too much load.
