### ISSUE TITLE
Reconnectivity issue when fetching on complete Block traces

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/EthVM#543]
* **I'm submitting a ...**
    - [x] bug report

* **Bug Report**

Here's a complete trace of the exception (feature/parity-processing-improvements):

```
[2019-06-01 ,888] ERROR ParitySourceTask - Exception detected (com.ethvm.kafka.connect.sources.web3.ParitySourceTask)
java.util.concurrent.TimeoutException
at java.util.concurrent.FutureTask.get(FutureTask.java:205)
at com.ethvm.kafka.connect.sources.web3.sources.ParityFullBlockSource.fetchRange(ParityFullBlockSource.kt:70)
at com.ethvm.kafka.connect.sources.web3.sources.AbstractParityEntitySource.poll(AbstractParityEntitySource.kt:60)
at com.ethvm.kafka.connect.sources.web3.ParitySourceTask.poll(ParitySourceTask.kt:63)
at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
[2019-06-01 ,890] ERROR WorkerSourceTask{id=parity-source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.util.concurrent.TimeoutException
at java.util.concurrent.FutureTask.get(FutureTask.java:205)
at com.ethvm.kafka.connect.sources.web3.sources.ParityFullBlockSource.fetchRange(ParityFullBlockSource.kt:70)
at com.ethvm.kafka.connect.sources.web3.sources.AbstractParityEntitySource.poll(AbstractParityEntitySource.kt:60)
at com.ethvm.kafka.connect.sources.web3.ParitySourceTask.poll(ParitySourceTask.kt:63)
at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
[2019-06-01 ,891] ERROR WorkerSourceTask{id=parity-source-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2019-06-01 ,891] DEBUG Stopping ParitySourceTask (com.ethvm.kafka.connect.sources.web3.ParitySourceTask)
[2019-06-01 ,898] WARN [Consumer clientId=consumer-134, groupId=connect-postgres-balance-delta-sink] Error while fetching metadata with correlation id 53515 : {non_fungible_balance_delta=UNKNOWN_TOPIC_OR_PARTITION} (org.apache.kafka.clients.NetworkClient)
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | null
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
at io.reactivex.internal.observers.DisposableLambdaObserver.dispose(DisposableLambdaObserver.java:83)
at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.cancel(FlowableFromObservable.java:64)
at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.cancel(FlowableOnBackpressureBuffer.java:151)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactBoundedSubscriber.dispose(FlowableBufferTimed.java:537)
at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactBoundedSubscriber.cancel(FlowableBufferTimed.java:528)
at io.reactivex.subscribers.SerializedSubscriber.cancel(SerializedSubscriber.java:197)
at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.cancel(FlowableOnBackpressureBuffer.java:151)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:189)
at io.reactivex.internal.subscribers.LambdaSubscriber.cancel(LambdaSubscriber.java:119)
at io.reactivex.internal.subscribers.LambdaSubscriber.dispose(LambdaSubscriber.java:104)
at com.ethvm.kafka.connect.sources.web3.tracker.CanonicalChainTracker.stop(CanonicalChainTracker.kt:71)
at com.ethvm.kafka.connect.sources.web3.sources.AbstractParityEntitySource.stop(AbstractParityEntitySource.kt:43)
at com.ethvm.kafka.connect.sources.web3.ParitySourceTask.stop(ParitySourceTask.kt:45)
at org.apache.kafka.connect.runtime.WorkerSourceTask.tryStop(WorkerSourceTask.java:187)
at org.apache.kafka.connect.runtime.WorkerSourceTask.close(WorkerSourceTask.java:151)
at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:154)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:181)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.java_websocket.exceptions.WebsocketNotConnectedException
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585)
at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:309)
at org.web3j.protocol.websocket.WebSocketService.sendRequest(WebSocketService.java:165)
at org.web3j.protocol.websocket.WebSocketService.sendAsync(WebSocketService.java:154)
at org.web3j.protocol.websocket.WebSocketService.unsubscribeFromEventsStream(WebSocketService.java:402)
at org.web3j.protocol.websocket.WebSocketService.closeSubscription(WebSocketService.java:395)
at org.web3j.protocol.websocket.WebSocketService.lambda$subscribe$2(WebSocketService.java:369)
at io.reactivex.internal.observers.DisposableLambdaObserver.dispose(DisposableLambdaObserver.java:80)
... 25 more
Exception in thread "pool-9-thread-4" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | null
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
at io.reactivex.internal.observers.DisposableLambdaObserver.dispose(DisposableLambdaObserver.java:83)
at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.cancel(FlowableFromObservable.java:64)
at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.cancel(FlowableOnBackpressureBuffer.java:151)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactBoundedSubscriber.dispose(FlowableBufferTimed.java:537)
at io.reactivex.internal.operators.flowable.FlowableBufferTimed$BufferExactBoundedSubscriber.cancel(FlowableBufferTimed.java:528)
at io.reactivex.subscribers.SerializedSubscriber.cancel(SerializedSubscriber.java:197)
at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.cancel(FlowableOnBackpressureBuffer.java:151)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.cancel(BasicFuseableSubscriber.java:158)
at io.reactivex.internal.subscriptions.SubscriptionHelper.cancel(SubscriptionHelper.java:189)
at io.reactivex.internal.subscribers.LambdaSubscriber.cancel(LambdaSubscriber.java:119)
at io.reactivex.internal.subscribers.LambdaSubscriber.dispose(LambdaSubscriber.java:104)
at com.ethvm.kafka.connect.sources.web3.tracker.CanonicalChainTracker.stop(CanonicalChainTracker.kt:71)
at com.ethvm.kafka.connect.sources.web3.sources.AbstractParityEntitySource.stop(AbstractParityEntitySource.kt:43)
at com.ethvm.kafka.connect.sources.web3.ParitySourceTask.stop(ParitySourceTask.kt:45)
at org.apache.kafka.connect.runtime.WorkerSourceTask.tryStop(WorkerSourceTask.java:187)
at org.apache.kafka.connect.runtime.WorkerSourceTask.close(WorkerSourceTask.java:151)
at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:154)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:181)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.java_websocket.exceptions.WebsocketNotConnectedException
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585)
at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:309)
at org.web3j.protocol.websocket.WebSocketService.sendRequest(WebSocketService.java:165)
at org.web3j.protocol.websocket.WebSocketService.sendAsync(WebSocketService.java:154)
at org.web3j.protocol.websocket.WebSocketService.unsubscribeFromEventsStream(WebSocketService.java:402)
at org.web3j.protocol.websocket.WebSocketService.closeSubscription(WebSocketService.java:395)
at org.web3j.protocol.websocket.WebSocketService.lambda$subscribe$2(WebSocketService.java:369)
at io.reactivex.internal.observers.DisposableLambdaObserver.dispose(DisposableLambdaObserver.java:80)
[2019-06-01 ,916] DEBUG Stopped ParitySourceTask (com.ethvm.kafka.connect.sources.web3.ParitySourceTask)
```

**Comment by aldoborrero** [comment]
This issue has been solved on `feature/parity-improvements` that is already merged on develop.

I proceed to close it
