### ISSUE TITLE
EthListsTokensSourceConnector processing error

### ISSUE THREAD

**Issue by brianmcgee** [EthVM/EthVM#574]
* **I'm submitting a ...**
    - [ ] feature request
    - [x] bug report

* **Bug Report**
    - What is the current behavior?

An exception is thrown in the mew-ethlists-source kafka connector.

```java
java.lang.IllegalArgumentException: No enum constant com.ethvm.avro.common.ContractType.Opiria & PDATA Token
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.ethvm.avro.common.ContractType.valueOf(ContractType.java:7)
	at com.ethvm.kafka.connect.sources.tokens.EthListsTokensSourceTask$ContractMetadata.toRecord(EthListsTokensSourceTask.kt:160)
	at com.ethvm.kafka.connect.sources.tokens.EthListsTokensSourceTask.poll(EthListsTokensSourceTask.kt:61)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by brianmcgee** [comment]
It appears to be an issue with the underlying source data from https://raw.githubusercontent.com/MyEtherWallet/ethereum-lists/master/dist/tokens/eth/tokens-eth.min.json. There is a bad entry:

```json
{"symbol":"PDATA","type":"Opiria & PDATA Token","address":"0x0db03B6CDe0B2d427C64a04FeAfd825938368f1F","decimals":18,"name":"PDATA","ens_address":"","website":"https://opiria.io","logo":{"src":"https://www.opiria.io/static/images/logo-solo.png","width":95,"height":110,"ipfs_hash":""},"support":{"email":"sales@opiria.com","url":"www.opiria.io"},"social":{"blog":"","chat":"","facebook":"","forum":"","github":"https://github.com/opiria-pdata/Pdata","gitter":"","instagram":"","linkedin":"","reddit":"","slack":"","telegram":"https://t.me/PDATAtoken","twitter":"","youtube":""}}
```

**Comment by brianmcgee** [comment]
Created an issue on MyEtherwallet/ethereum-lists https://github.com/MyEtherWallet/ethereum-lists/issues/1136
