### ISSUE TITLE
You might need to increase max_locks_per_transaction

### ISSUE THREAD

**Issue by aldoborrero** [EthVM/EthVM#589]
* **I'm submitting a ...**
    - [ ] feature request
    - [x] bug report

* **Bug Report**

```
[2019-06-12 16:59:28,760] DEBUG Next = 5627096..5627138 (com.ethvm.kafka.connect.sources.web3.sources.ParityFullBlockSource)
[2019-06-12 16:59:28,996] WARN Write of 500 records failed, remainingRetries=1 (io.confluent.connect.jdbc.sink.JdbcSinkTask)
java.sql.BatchUpdateException: Batch entry 223 INSERT INTO "transaction_trace" ("block_hash","transaction_hash","root_error","timestamp","trace_count","traces") VALUES ('0x68a360c0fc5c04458430ef1ea8b556815d4c576111a321d9feae98728c16b9b7','0x4405cca01999977cc03ec5c8fd40b269ec0658be06ba6da6d794cbfcf37475e9',NULL,'2018-07-16 00:37:34+00'::timestamp,1,'[
{
    "action": {
        "TraceRewardActionRecord": null,
        "TraceCallActionRecord": {
            "callType": "call",
            "from": "0x687422eea2cb73b5d3e242ba5456b782919afc85",
            "to": "0x0d19dcfa70ed06f6dac909abeee33ccd130d9a62",
            "gas": 293150,
            "input": "",
            "value": 1000000000000000000
        },
        "TraceCreateActionRecord": null,
        "TraceDestroyActionRecord": null
    },
    "error": null,
    "result": {
        "address": null,
        "code": null,
        "gasUsed": 0,
        "output": "0x"
    },
    "subtraces": 0,
    "traceAddress": [],
    "type": "call",
    "blockHash": "0x68a360c0fc5c04458430ef1ea8b556815d4c576111a321d9feae98728c16b9b7",
    "blockNumber": 3645736,
    "timestamp": null,
    "transactionHash": "0x4405cca01999977cc03ec5c8fd40b269ec0658be06ba6da6d794cbfcf37475e9",
    "transactionPosition": 12
}
]') ON CONFLICT ("block_hash","transaction_hash") DO UPDATE SET "root_error"=EXCLUDED."root_error","timestamp"=EXCLUDED."timestamp","trace_count"=EXCLUDED."trace_count","traces"=EXCLUDED."traces" was aborted: ERROR: out of shared memory
Hint: You might need to increase max_locks_per_transaction. Call getNextException to see other errors in the batch.
at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:145)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2156)
at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1265)
at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1290)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:446)
at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:793)
at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1659)
at io.confluent.connect.jdbc.sink.BufferedRecords.flush(BufferedRecords.java:143)
at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:72)
at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: out of shared memory
Hint: You might need to increase max_locks_per_transaction.
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
... 19 more
```

**Comment by aldoborrero** [comment]
@brianmcgee I think that this one have been solved so I'll mark the issue as closed (re-open if necessary)
